-- MySQL Script generated by MySQL Workbench
-- mar 05 jul 2022 20:55:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotify-DDBB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Spotify-DDBB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotify-DDBB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema spotify-ddbb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify-ddbb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify-ddbb` DEFAULT CHARACTER SET utf8mb3 ;
USE `Spotify-DDBB` ;

-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`codi postal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`codi postal` (
  `idcodi postal` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(60) NULL,
  `codi postal` VARCHAR(40) NULL,
  PRIMARY KEY (`idcodi postal`),
  UNIQUE INDEX `idcodi postal_UNIQUE` (`idcodi postal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`pais` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(60) NULL,
  PRIMARY KEY (`idtable1`),
  UNIQUE INDEX `idtable1_UNIQUE` (`idtable1` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`sexe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`sexe` (
  `idsexe` INT NOT NULL AUTO_INCREMENT,
  `sexe` VARCHAR(10) NULL,
  PRIMARY KEY (`idsexe`),
  UNIQUE INDEX `idsexe_UNIQUE` (`idsexe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`subscripcio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`subscripcio` (
  `idsubscripcio` INT NOT NULL AUTO_INCREMENT,
  `data de inici` DATETIME(6) NULL,
  `data renovacio` DATETIME(6) NULL,
  `forma de pagament` VARCHAR(45) NULL,
  `data de pagament` DATETIME NULL,
  `numero de ordre` INT NULL,
  `quantitat pagada` FLOAT NULL,
  PRIMARY KEY (`idsubscripcio`),
  UNIQUE INDEX `idsubscripcio_UNIQUE` (`idsubscripcio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`usuari` (
  `idusuari` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `nom de usuari` VARCHAR(60) NOT NULL,
  `data naixement` DATE NOT NULL,
  `sexe_idsexe` INT NOT NULL,
  `pais_idtable1` INT NOT NULL,
  `codi postal_idcodi postal` INT NOT NULL,
  `subscripcio_idsubscripcio` INT NULL,
  `subscripcio en actiu` BINARY(1) NOT NULL,
  PRIMARY KEY (`idusuari`, `sexe_idsexe`, `pais_idtable1`, `codi postal_idcodi postal`, `subscripcio_idsubscripcio`),
  UNIQUE INDEX `idusuari_UNIQUE` (`idusuari` ASC) VISIBLE,
  INDEX `fk_usuari_codi postal1_idx` (`codi postal_idcodi postal` ASC) VISIBLE,
  INDEX `fk_usuari_pais1_idx` (`pais_idtable1` ASC) VISIBLE,
  INDEX `fk_usuari_sexe1_idx` (`sexe_idsexe` ASC) VISIBLE,
  INDEX `fk_usuari_subscripcio1_idx` (`subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_codi postal1`
    FOREIGN KEY (`codi postal_idcodi postal`)
    REFERENCES `Spotify-DDBB`.`codi postal` (`idcodi postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuari_pais1`
    FOREIGN KEY (`pais_idtable1`)
    REFERENCES `Spotify-DDBB`.`pais` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuari_sexe1`
    FOREIGN KEY (`sexe_idsexe`)
    REFERENCES `Spotify-DDBB`.`sexe` (`idsexe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuari_subscripcio1`
    FOREIGN KEY (`subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`subscripcio` (`idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`targeta de credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`targeta de credit` (
  `idtargeta de credit` INT NOT NULL AUTO_INCREMENT,
  `numero de targeta` VARCHAR(45) NOT NULL,
  `mes de caducitat` VARCHAR(20) NOT NULL,
  `any de caducitat` YEAR(4) NOT NULL,
  `cvc` INT(3) NOT NULL,
  `subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`idtargeta de credit`, `subscripcio_idsubscripcio`),
  UNIQUE INDEX `idtargeta de credit_UNIQUE` (`idtargeta de credit` ASC) VISIBLE,
  INDEX `fk_targeta de credit_subscripcio1_idx` (`subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_targeta de credit_subscripcio1`
    FOREIGN KEY (`subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`subscripcio` (`idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`paypal` (
  `idpaypal` INT NOT NULL AUTO_INCREMENT,
  `nom de usuari` VARCHAR(60) NOT NULL,
  `subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`idpaypal`, `subscripcio_idsubscripcio`),
  UNIQUE INDEX `idpaypal_UNIQUE` (`idpaypal` ASC) VISIBLE,
  INDEX `fk_paypal_subscripcio1_idx` (`subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_paypal_subscripcio1`
    FOREIGN KEY (`subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`subscripcio` (`idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`artista` (
  `idartista` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NULL,
  `password` VARCHAR(60) NULL,
  `nom de usuari` VARCHAR(60) NULL,
  `imatge` BLOB NULL,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  `artista_idartista` INT NOT NULL,
  PRIMARY KEY (`idartista`),
  UNIQUE INDEX `idartista_UNIQUE` (`idartista` ASC) VISIBLE,
  INDEX `fk_artista_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  INDEX `fk_artista_artista1_idx` (`artista_idartista` ASC) VISIBLE,
  CONSTRAINT `fk_artista_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artista_artista1`
    FOREIGN KEY (`artista_idartista`)
    REFERENCES `Spotify-DDBB`.`artista` (`idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`playlist` (
  `idplaylist` INT NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(100) NOT NULL,
  `data de creacio` DATETIME NOT NULL,
  `numero de cancons` INT NOT NULL,
  `playlist compartida` BINARY(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idplaylist`),
  UNIQUE INDEX `idplaylist_UNIQUE` (`idplaylist` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`usuari_has_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`usuari_has_playlist` (
  `playlist_idplaylist` INT NOT NULL,
  `playlist esborrada` BINARY(1) NOT NULL DEFAULT 0,
  `modificacio` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NULL,
  `usuari creador` BINARY(1) NOT NULL,
  PRIMARY KEY (`playlist_idplaylist`),
  INDEX `fk_usuari_has_playlist_playlist1_idx` (`playlist_idplaylist` ASC) VISIBLE,
  INDEX `fk_usuari_has_playlist_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_has_playlist_playlist1`
    FOREIGN KEY (`playlist_idplaylist`)
    REFERENCES `Spotify-DDBB`.`playlist` (`idplaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuari_has_playlist_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`album` (
  `idalbum` INT NOT NULL AUTO_INCREMENT,
  `artista_idartista` INT NOT NULL,
  `titulo` VARCHAR(60) NULL,
  `any` INT(4) NULL,
  `imatge portada` BLOB NULL,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`idalbum`, `artista_idartista`),
  UNIQUE INDEX `idalbum_UNIQUE` (`idalbum` ASC) VISIBLE,
  INDEX `fk_album_artista1_idx` (`artista_idartista` ASC) VISIBLE,
  INDEX `fk_album_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_idartista`)
    REFERENCES `Spotify-DDBB`.`artista` (`idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`canciones` (
  `idcanciones` INT NOT NULL AUTO_INCREMENT,
  `album_idalbum` INT NOT NULL,
  `titol` VARCHAR(45) NULL,
  `durada` VARCHAR(45) NULL,
  `reproduccions` INT(20) ZEROFILL NULL,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`idcanciones`, `album_idalbum`),
  UNIQUE INDEX `idcanciones_UNIQUE` (`idcanciones` ASC) VISIBLE,
  INDEX `fk_canciones_album1_idx` (`album_idalbum` ASC) VISIBLE,
  INDEX `fk_canciones_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_canciones_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `Spotify-DDBB`.`album` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canciones_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`playlist_has_canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`playlist_has_canciones` (
  `playlist_idplaylist` INT NOT NULL,
  `canciones_idcanciones` INT NOT NULL,
  `canciones_album_idalbum` INT NOT NULL,
  `album_idalbum` INT NOT NULL,
  `album_artista_idartista` INT NOT NULL,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`playlist_idplaylist`, `usuari_idusuari`, `usuari_sexe_idsexe`, `usuari_pais_idtable1`, `usuari_codi postal_idcodi postal`, `usuari_subscripcio_idsubscripcio`),
  INDEX `fk_playlist_has_artista_playlist1_idx` (`playlist_idplaylist` ASC) VISIBLE,
  INDEX `fk_playlist_has_canciones_canciones1_idx` (`canciones_idcanciones` ASC, `canciones_album_idalbum` ASC) VISIBLE,
  INDEX `fk_playlist_has_canciones_album1_idx` (`album_idalbum` ASC, `album_artista_idartista` ASC) VISIBLE,
  INDEX `fk_playlist_has_canciones_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_has_artista_playlist1`
    FOREIGN KEY (`playlist_idplaylist`)
    REFERENCES `Spotify-DDBB`.`playlist` (`idplaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_has_canciones_canciones1`
    FOREIGN KEY (`canciones_idcanciones` , `canciones_album_idalbum`)
    REFERENCES `Spotify-DDBB`.`canciones` (`idcanciones` , `album_idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_has_canciones_album1`
    FOREIGN KEY (`album_idalbum` , `album_artista_idartista`)
    REFERENCES `Spotify-DDBB`.`album` (`idalbum` , `artista_idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_has_canciones_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify-DDBB`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify-DDBB`.`favoritos` (
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  `album_idalbum` INT NOT NULL,
  `album_artista_idartista` INT NOT NULL,
  `canciones_idcanciones` INT NOT NULL,
  `canciones_album_idalbum` INT NOT NULL,
  PRIMARY KEY (`usuari_idusuari`, `usuari_sexe_idsexe`, `usuari_pais_idtable1`, `usuari_codi postal_idcodi postal`, `usuari_subscripcio_idsubscripcio`, `album_idalbum`, `album_artista_idartista`, `canciones_idcanciones`, `canciones_album_idalbum`),
  INDEX `fk_usuari_has_album_album1_idx` (`album_idalbum` ASC, `album_artista_idartista` ASC) VISIBLE,
  INDEX `fk_usuari_has_album_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  INDEX `fk_favoritos_canciones1_idx` (`canciones_idcanciones` ASC, `canciones_album_idalbum` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_has_album_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `Spotify-DDBB`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuari_has_album_album1`
    FOREIGN KEY (`album_idalbum` , `album_artista_idartista`)
    REFERENCES `Spotify-DDBB`.`album` (`idalbum` , `artista_idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_canciones1`
    FOREIGN KEY (`canciones_idcanciones` , `canciones_album_idalbum`)
    REFERENCES `Spotify-DDBB`.`canciones` (`idcanciones` , `album_idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `spotify-ddbb` ;

-- -----------------------------------------------------
-- Table `spotify-ddbb`.`codi postal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`codi postal` (
  `idcodi postal` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(60) NULL DEFAULT NULL,
  `codi postal` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`idcodi postal`),
  UNIQUE INDEX `idcodi postal_UNIQUE` (`idcodi postal` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`pais` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`idtable1`),
  UNIQUE INDEX `idtable1_UNIQUE` (`idtable1` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`sexe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`sexe` (
  `idsexe` INT NOT NULL AUTO_INCREMENT,
  `sexe` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsexe`),
  UNIQUE INDEX `idsexe_UNIQUE` (`idsexe` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`subscripcio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`subscripcio` (
  `idsubscripcio` INT NOT NULL AUTO_INCREMENT,
  `data de inici` DATETIME(6) NULL DEFAULT NULL,
  `data renovacio` DATETIME(6) NULL DEFAULT NULL,
  `forma de pagament` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsubscripcio`),
  UNIQUE INDEX `idsubscripcio_UNIQUE` (`idsubscripcio` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`usuari` (
  `idusuari` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `nom de usuari` VARCHAR(60) NOT NULL,
  `data naixement` DATE NOT NULL,
  `sexe_idsexe` INT NOT NULL,
  `pais_idtable1` INT NOT NULL,
  `codi postal_idcodi postal` INT NOT NULL,
  `subscripcio_idsubscripcio` INT NOT NULL,
  `subscripcio en actiu` BINARY(1) NOT NULL,
  PRIMARY KEY (`idusuari`, `sexe_idsexe`, `pais_idtable1`, `codi postal_idcodi postal`, `subscripcio_idsubscripcio`),
  UNIQUE INDEX `idusuari_UNIQUE` (`idusuari` ASC) VISIBLE,
  INDEX `fk_usuari_codi postal1_idx` (`codi postal_idcodi postal` ASC) VISIBLE,
  INDEX `fk_usuari_pais1_idx` (`pais_idtable1` ASC) VISIBLE,
  INDEX `fk_usuari_sexe1_idx` (`sexe_idsexe` ASC) VISIBLE,
  INDEX `fk_usuari_subscripcio1_idx` (`subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_codi postal1`
    FOREIGN KEY (`codi postal_idcodi postal`)
    REFERENCES `spotify-ddbb`.`codi postal` (`idcodi postal`),
  CONSTRAINT `fk_usuari_pais1`
    FOREIGN KEY (`pais_idtable1`)
    REFERENCES `spotify-ddbb`.`pais` (`idtable1`),
  CONSTRAINT `fk_usuari_sexe1`
    FOREIGN KEY (`sexe_idsexe`)
    REFERENCES `spotify-ddbb`.`sexe` (`idsexe`),
  CONSTRAINT `fk_usuari_subscripcio1`
    FOREIGN KEY (`subscripcio_idsubscripcio`)
    REFERENCES `spotify-ddbb`.`subscripcio` (`idsubscripcio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`artista` (
  `idartista` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `password` VARCHAR(60) NULL DEFAULT NULL,
  `nom de usuari` VARCHAR(60) NULL DEFAULT NULL,
  `imatge` BLOB NULL DEFAULT NULL,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  `artista_idartista` INT NOT NULL,
  PRIMARY KEY (`idartista`),
  UNIQUE INDEX `idartista_UNIQUE` (`idartista` ASC) VISIBLE,
  INDEX `fk_artista_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  INDEX `fk_artista_artista1_idx` (`artista_idartista` ASC) VISIBLE,
  CONSTRAINT `fk_artista_artista1`
    FOREIGN KEY (`artista_idartista`)
    REFERENCES `spotify-ddbb`.`artista` (`idartista`),
  CONSTRAINT `fk_artista_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `spotify-ddbb`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`album` (
  `idalbum` INT NOT NULL AUTO_INCREMENT,
  `artista_idartista` INT NOT NULL,
  `titulo` VARCHAR(60) NULL DEFAULT NULL,
  `any` INT NULL DEFAULT NULL,
  `imatge portada` BLOB NULL DEFAULT NULL,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`idalbum`, `artista_idartista`),
  UNIQUE INDEX `idalbum_UNIQUE` (`idalbum` ASC) VISIBLE,
  INDEX `fk_album_artista1_idx` (`artista_idartista` ASC) VISIBLE,
  INDEX `fk_album_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_idartista`)
    REFERENCES `spotify-ddbb`.`artista` (`idartista`),
  CONSTRAINT `fk_album_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `spotify-ddbb`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`canciones` (
  `idcanciones` INT NOT NULL AUTO_INCREMENT,
  `album_idalbum` INT NOT NULL,
  `titol` VARCHAR(45) NULL DEFAULT NULL,
  `durada` VARCHAR(45) NULL DEFAULT NULL,
  `reproduccions` INT NULL DEFAULT NULL,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`idcanciones`, `album_idalbum`),
  UNIQUE INDEX `idcanciones_UNIQUE` (`idcanciones` ASC) VISIBLE,
  INDEX `fk_canciones_album1_idx` (`album_idalbum` ASC) VISIBLE,
  INDEX `fk_canciones_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_canciones_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `spotify-ddbb`.`album` (`idalbum`),
  CONSTRAINT `fk_canciones_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `spotify-ddbb`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`paypal` (
  `idpaypal` INT NOT NULL AUTO_INCREMENT,
  `compte` VARCHAR(60) NOT NULL,
  `subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`idpaypal`, `subscripcio_idsubscripcio`),
  UNIQUE INDEX `idpaypal_UNIQUE` (`idpaypal` ASC) VISIBLE,
  INDEX `fk_paypal_subscripcio1_idx` (`subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_paypal_subscripcio1`
    FOREIGN KEY (`subscripcio_idsubscripcio`)
    REFERENCES `spotify-ddbb`.`subscripcio` (`idsubscripcio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`playlist` (
  `idplaylist` INT NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(45) NULL DEFAULT NULL,
  `data de creacio` VARCHAR(45) NULL DEFAULT NULL,
  `numero de cancons` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idplaylist`),
  UNIQUE INDEX `idplaylist_UNIQUE` (`idplaylist` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`playlist_has_canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`playlist_has_canciones` (
  `playlist_idplaylist` INT NOT NULL,
  `canciones_idcanciones` INT NOT NULL,
  `canciones_album_idalbum` INT NOT NULL,
  `album_idalbum` INT NOT NULL,
  `album_artista_idartista` INT NOT NULL,
  PRIMARY KEY (`playlist_idplaylist`),
  INDEX `fk_playlist_has_artista_playlist1_idx` (`playlist_idplaylist` ASC) VISIBLE,
  INDEX `fk_playlist_has_canciones_canciones1_idx` (`canciones_idcanciones` ASC, `canciones_album_idalbum` ASC) VISIBLE,
  INDEX `fk_playlist_has_canciones_album1_idx` (`album_idalbum` ASC, `album_artista_idartista` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_has_artista_playlist1`
    FOREIGN KEY (`playlist_idplaylist`)
    REFERENCES `spotify-ddbb`.`playlist` (`idplaylist`),
  CONSTRAINT `fk_playlist_has_canciones_album1`
    FOREIGN KEY (`album_idalbum` , `album_artista_idartista`)
    REFERENCES `spotify-ddbb`.`album` (`idalbum` , `artista_idartista`),
  CONSTRAINT `fk_playlist_has_canciones_canciones1`
    FOREIGN KEY (`canciones_idcanciones` , `canciones_album_idalbum`)
    REFERENCES `spotify-ddbb`.`canciones` (`idcanciones` , `album_idalbum`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`targeta de credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`targeta de credit` (
  `idtargeta de credit` INT NOT NULL AUTO_INCREMENT,
  `numero de targeta` VARCHAR(45) NOT NULL,
  `mes de caducitat` VARCHAR(20) NOT NULL,
  `any de caducitat` YEAR NOT NULL,
  `cvc` INT NOT NULL,
  `subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`idtargeta de credit`, `subscripcio_idsubscripcio`),
  UNIQUE INDEX `idtargeta de credit_UNIQUE` (`idtargeta de credit` ASC) VISIBLE,
  INDEX `fk_targeta de credit_subscripcio1_idx` (`subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_targeta de credit_subscripcio1`
    FOREIGN KEY (`subscripcio_idsubscripcio`)
    REFERENCES `spotify-ddbb`.`subscripcio` (`idsubscripcio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-ddbb`.`usuari_has_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-ddbb`.`usuari_has_playlist` (
  `playlist_idplaylist` INT NOT NULL,
  `playlist esborrada` BINARY(1) NOT NULL DEFAULT '0',
  `modificacio` DATETIME NULL DEFAULT NULL,
  `usuari_idusuari` INT NOT NULL,
  `usuari_sexe_idsexe` INT NOT NULL,
  `usuari_pais_idtable1` INT NOT NULL,
  `usuari_codi postal_idcodi postal` INT NOT NULL,
  `usuari_subscripcio_idsubscripcio` INT NOT NULL,
  PRIMARY KEY (`playlist_idplaylist`),
  INDEX `fk_usuari_has_playlist_playlist1_idx` (`playlist_idplaylist` ASC) VISIBLE,
  INDEX `fk_usuari_has_playlist_usuari1_idx` (`usuari_idusuari` ASC, `usuari_sexe_idsexe` ASC, `usuari_pais_idtable1` ASC, `usuari_codi postal_idcodi postal` ASC, `usuari_subscripcio_idsubscripcio` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_has_playlist_playlist1`
    FOREIGN KEY (`playlist_idplaylist`)
    REFERENCES `spotify-ddbb`.`playlist` (`idplaylist`),
  CONSTRAINT `fk_usuari_has_playlist_usuari1`
    FOREIGN KEY (`usuari_idusuari` , `usuari_sexe_idsexe` , `usuari_pais_idtable1` , `usuari_codi postal_idcodi postal` , `usuari_subscripcio_idsubscripcio`)
    REFERENCES `spotify-ddbb`.`usuari` (`idusuari` , `sexe_idsexe` , `pais_idtable1` , `codi postal_idcodi postal` , `subscripcio_idsubscripcio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
