-- MySQL Script generated by MySQL Workbench
-- dom 03 jul 2022 18:43:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`proveidor` (
  `idproveidor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  `telefon` INT(13) ZEROFILL NOT NULL,
  `fax` INT(13) ZEROFILL NULL,
  `NIF` VARCHAR(30) NULL,
  PRIMARY KEY (`idproveidor`),
  UNIQUE INDEX `idproveidor_UNIQUE` (`idproveidor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`adreça_proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`adreça_proveidor` (
  `idadreça proveidor` INT NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(60) NULL,
  `numero` INT(15) ZEROFILL NULL,
  `pis` VARCHAR(12) NULL,
  `porta` INT(10) ZEROFILL NULL,
  `ciutat` VARCHAR(60) NULL,
  `codi postal` INT(5) NULL,
  `pais` VARCHAR(60) NULL,
  `proveidor_idproveidor` INT NOT NULL,
  PRIMARY KEY (`idadreça proveidor`, `proveidor_idproveidor`),
  UNIQUE INDEX `idadreça proveidor_UNIQUE` (`idadreça proveidor` ASC) VISIBLE,
  INDEX `fk_adreça proveidor_proveidor1_idx` (`proveidor_idproveidor` ASC) VISIBLE,
  CONSTRAINT `fk_adreça proveidor_proveidor1`
    FOREIGN KEY (`proveidor_idproveidor`)
    REFERENCES `Optica`.`proveidor` (`idproveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`tipus_de_muntura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`tipus_de_muntura` (
  `idtipus de muntura` INT NOT NULL AUTO_INCREMENT,
  `tipus de muntura` VARCHAR(10) NULL,
  PRIMARY KEY (`idtipus de muntura`),
  UNIQUE INDEX `idtipus de muntura_UNIQUE` (`idtipus de muntura` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`empleat` (
  `idempleat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idempleat`),
  UNIQUE INDEX `idempleat_UNIQUE` (`idempleat` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  `telefon` INT(16) ZEROFILL NOT NULL,
  `email` VARCHAR(60) NULL,
  `data de registre` DATE NULL,
  `client_idclient` INT NULL,
  `empleat_idempleat` INT NOT NULL,
  PRIMARY KEY (`idclient`, `empleat_idempleat`),
  UNIQUE INDEX `idclient_UNIQUE` (`idclient` ASC) VISIBLE,
  INDEX `fk_client_client1_idx` (`client_idclient` ASC) VISIBLE,
  INDEX `fk_client_empleat1_idx` (`empleat_idempleat` ASC) VISIBLE,
  CONSTRAINT `fk_client_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `Optica`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_empleat1`
    FOREIGN KEY (`empleat_idempleat`)
    REFERENCES `Optica`.`empleat` (`idempleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`adreça_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`adreça_client` (
  `idadreça proveidor` INT NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(60) NULL,
  `numero` INT(15) ZEROFILL NULL,
  `pis` VARCHAR(12) NULL,
  `porta` INT(10) ZEROFILL NULL,
  `ciutat` VARCHAR(60) NOT NULL,
  `codi postal` INT(5) NOT NULL,
  `pais` VARCHAR(60) NOT NULL,
  `client_idclient` INT NOT NULL,
  PRIMARY KEY (`idadreça proveidor`, `client_idclient`),
  UNIQUE INDEX `idadreça proveidor_UNIQUE` (`idadreça proveidor` ASC) VISIBLE,
  INDEX `fk_adreça client_client1_idx` (`client_idclient` ASC) VISIBLE,
  CONSTRAINT `fk_adreça client_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `Optica`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`ulleres_vendes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`ulleres_vendes` (
  `idcompres` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(60) NOT NULL,
  `preu` FLOAT NOT NULL,
  `color de la muntura` VARCHAR(30) NOT NULL,
  `graduacio vidre dret` FLOAT NOT NULL,
  `graduacio vidre esquerre` FLOAT NOT NULL,
  `color vidre dret` VARCHAR(30) NOT NULL,
  `color vidre esquerre` VARCHAR(30) NOT NULL,
  `tipus de muntura_idtipus de muntura` INT NOT NULL,
  `client_idclient` INT NOT NULL,
  `empleat_idempleat` INT NOT NULL,
  `proveidor_idproveidor` INT NOT NULL,
  PRIMARY KEY (`idcompres`),
  UNIQUE INDEX `idcompres_UNIQUE` (`idcompres` ASC) VISIBLE,
  INDEX `fk_compres_tipus de muntura1_idx` (`tipus de muntura_idtipus de muntura` ASC) VISIBLE,
  INDEX `fk_ulleres_client1_idx` (`client_idclient` ASC) VISIBLE,
  INDEX `fk_ulleres_empleat1_idx` (`empleat_idempleat` ASC) VISIBLE,
  INDEX `fk_ulleres - vendes_proveidor1_idx` (`proveidor_idproveidor` ASC) VISIBLE,
  CONSTRAINT `fk_compres_tipus de muntura10`
    FOREIGN KEY (`tipus de muntura_idtipus de muntura`)
    REFERENCES `Optica`.`tipus_de_muntura` (`idtipus de muntura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulleres_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `Optica`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulleres_empleat1`
    FOREIGN KEY (`empleat_idempleat`)
    REFERENCES `Optica`.`empleat` (`idempleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulleres - vendes_proveidor1`
    FOREIGN KEY (`proveidor_idproveidor`)
    REFERENCES `Optica`.`proveidor` (`idproveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
